# **1차원 데이터**

In [1]:
import numpy as np
import pandas as pd
# Jupyter에서 출력의 소수점을 3자리로 제한
%precision 3
pd.set_option('precision',3)
df = pd.read_csv('./data/ch2_scores_em.csv', index_col = 'student number')

In [2]:
df.head(3)

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63

In [3]:
df.shape

(50, 2)

In [14]:
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [15]:
scores = df.loc[1:10, 'english'].to_numpy(dtype = np.float64)
scores

array([42., 69., 56., 41., 57., 48., 65., 49., 65., 58.])

In [16]:
scores = df.loc[1:10, 'english']
scores

student number
1     42
2     69
3     56
4     41
5     57
6     48
7     65
8     49
9     65
10    58
Name: english, dtype: int64

In [19]:
scores = df.iloc[:10, 0]
scores

student number
1     42
2     69
3     56
4     41
5     57
6     48
7     65
8     49
9     65
10    58
Name: english, dtype: int64

In [20]:
# 평균
sum(scores)/len(scores)

55.000

In [21]:
np.mean(scores)

55.000

In [22]:
df['english'].mean()

58.380

In [23]:
# 중앙값
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [26]:
n = len(sorted_scores)
if n % 2 ==0:
    m0 = sorted_scores[n//2 - 1]
    m1 = sorted_scores[n//2]
    median = (m0 + m1) / 2
else:
    median = sorted_scores[(n+1)//2 - 1]

In [27]:
median

56.5

In [24]:
np.median(scores)

56.5

In [25]:
df['english'].median()

57.500

In [28]:
# 최빈값
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

# **데이터의 산포도 지표**
#### **- 분산과 표준편차**

In [32]:
# 편차
mean = np.mean(scores)
deviation = scores - mean
deviation

student number
1    -13.0
2     14.0
3      1.0
4    -14.0
5      2.0
6     -7.0
7     10.0
8     -6.0
9     10.0
10     3.0
Name: english, dtype: float64

In [33]:
another_score = [50, 60, 58, 54, 51, 56, 57, 53, 52, 59]
another_mean = np.mean(another_score)
another_deviation = another_score - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [34]:
np.mean(deviation)

0.000

In [35]:
np.mean(another_deviation)

0.0

In [36]:
# 분산
np.mean(deviation ** 2)

86.000

In [37]:
np.var(deviation)

86.000

In [38]:
# 모집단
np.var(scores, ddof = 0)

86.000

In [39]:
# 표본집단
np.var(scores, ddof = 1)

95.556

In [40]:
# 표준편차
np.sqrt(np.var(scores, ddof = 0))

9.273618495495704

In [41]:
np.std(scores, ddof=0)

9.274

In [42]:
# 범위 4분위수
np.max(scores) - np.min(scores)

28

In [43]:
scores_Q1 = np.percentile(scores,25)
scores_Q3 = np.percentile(scores, 75)
scores_IQR = scores_Q3 - scores_Q1
scores_IQR

15.0