In [9]:
import numpy as np

In [7]:
%%time
x=0
y=0
for i in range(100,1000):
    for j in range(100,1000):
        if str(i*j)==str(i*j)[::-1] and x<i*j:
            if x < i*j:
                x=i*j

Wall time: 499 ms


In [8]:
x

906609

In [15]:
score=np.random.randint(1,100,100)

In [16]:
grade=[]
for i in score:
    if i>=90:
        grade.append('A')
    elif i>=80:
        grade.append('B')
    elif i>= 70:
        grade.append('C')
    else:
        grade.append('D')

In [18]:
score

array([38, 77, 51, 31, 58, 85, 78, 95,  5,  3,  8, 56, 80, 31, 42, 82, 65,
       13,  9, 94, 92,  2, 97,  4, 80,  2, 90, 18, 24, 90, 10, 66, 28, 41,
       28,  6, 19,  4,  7, 24, 43, 85, 27, 38, 73, 38, 22, 61, 52, 50, 32,
       27,  4,  3,  1, 98, 70, 22, 15, 55, 72, 56, 94, 26, 30, 58, 72, 98,
       15,  8, 99, 89, 23, 41, 84, 33, 49, 62, 25, 61, 55, 25, 10, 67, 52,
       84, 52,  6, 32, 72, 16, 22, 62, 24, 51, 77, 75, 81, 44, 70])

In [23]:
def and_bool(x,y):
    return x+y==2

In [24]:
and_bool(True,False)

False

In [27]:
def or_bool(x,y):
    return x+y>=1

In [28]:
or_bool(True,False)

True

In [30]:
def xor_bool(x,y):
    return x+y==1

In [32]:
xor_bool(True,True)

False

In [33]:
x=[[1,2,3],[4,5,6]]

In [35]:
x[0][1:3]

[2, 3]

In [36]:
import pandas as pd

In [37]:
import matplotlib.pyplot as plt

In [ ]:
engine = create_

In [72]:
from sqlalchemy import create_engine
import cx_Oracle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

engine=create_engine('oracle://c##big:123@localhost:1521/orcl’)
iris = pd.read_sql_query('select * from iris’,con=engine)
df=pd.read_sql_query('select * from iris', con=engine)
df.loc[df.sp="setosa",'sp']

SyntaxError: EOL while scanning string literal (<ipython-input-72-5604dcea007d>, line 7)

In [8]:
from sklearn.datasets import load_wine, load_boston
import numpy as np
import pandas as pd

In [4]:
boston_data=load_boston()
wine_data=load_wine()

In [9]:
boston_df = pd.DataFrame(boston_data['data'])

In [13]:
boston_df.columns=boston_data['feature_names']

In [15]:
boston_df1=boston_df.iloc[:,:7]
boston_df2=boston_df.iloc[:,7:]

In [19]:
boston_df1

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2
..       ...   ...    ...   ...    ...    ...   ...
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8

[506 rows x 7 columns]

In [20]:
boston_df1.dtypes

CRIM     float64
ZN       float64
INDUS    float64
CHAS     float64
NOX      float64
RM       float64
AGE      float64
dtype: object

In [21]:
boston_df2.dtypes

DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
dtype: object

In [22]:
import numpy as np
import pandas as pd

In [101]:
x=[]
for i in [1,2,3]:
    x.append(i*4)
x

[4, 8, 12]

In [102]:
np.array([1,2,3])*4

array([ 4,  8, 12])

In [103]:
np.array(np.arange(10)).reshape(2,5,1).ndim

3

In [104]:
x=pd.Series(x)
x[0]
x+3

0     7
1    11
2    15
dtype: int64

In [105]:
y=pd.DataFrame(x)
print(x.values)
print(y.values)

[ 4  8 12]
[[ 4]
 [ 8]
 [12]]


In [106]:
y.columns

RangeIndex(start=0, stop=1, step=1)

In [107]:
y.columns=['col_name1']

In [108]:
y

col_name1
0          4
1          8
2         12

In [109]:
y['col_name2']=x+3

In [110]:
y.index=['one','two','three']

In [111]:
y

col_name1  col_name2
one            4          7
two            8         11
three         12         15

In [88]:
# y에서 col_name2의 가장 큰 값을 찾고 해당 row의 col_name1값을 찾으시오.

In [120]:
y.col_name2.max()

15

In [63]:
x=np.array([5,2,3,4])

In [68]:
x[[True,False,False,True]]

array([5, 4])

In [70]:
x[x>3]

array([5, 4])

In [115]:
y.iloc[2,0]

12

In [ ]:
y.iloc[y.col_name2==y.col_name2.max()]

In [118]:
y.reset_index().index[(y.col_name2==y.col_name2.max())]

Int64Index([2], dtype='int64')

In [119]:
y.iloc[y.reset_index().index[(y.col_name2==y.col_name2.max())],0]

three    12
Name: col_name1, dtype: int64

In [74]:
x=['1','2','3']
y=list(map(int,x))

In [77]:
x=pd.Series(['1','2','3']).apply(int)
y=list(x)

In [78]:
x

0    1
1    2
2    3
dtype: int64

In [79]:
y

[1, 2, 3]

In [121]:
boston_df1

## insert into boston_master(seq,crim,zn,indus,chas,nox,rm,age) values(0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2
..       ...   ...    ...   ...    ...    ...   ...
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8

[506 rows x 7 columns]

In [126]:
boston_df1.to_excel('boston_df1.xlsx')

In [127]:
boston_df2

DIS  RAD    TAX  PTRATIO       B  LSTAT
0    4.0900  1.0  296.0     15.3  396.90   4.98
1    4.9671  2.0  242.0     17.8  396.90   9.14
2    4.9671  2.0  242.0     17.8  392.83   4.03
3    6.0622  3.0  222.0     18.7  394.63   2.94
4    6.0622  3.0  222.0     18.7  396.90   5.33
..      ...  ...    ...      ...     ...    ...
501  2.4786  1.0  273.0     21.0  391.99   9.67
502  2.2875  1.0  273.0     21.0  396.90   9.08
503  2.1675  1.0  273.0     21.0  396.90   5.64
504  2.3889  1.0  273.0     21.0  393.45   6.48
505  2.5050  1.0  273.0     21.0  396.90   7.88

[506 rows x 6 columns]

In [163]:

for i in boston_df2.index:
    print(stmt,(i,)+tuple(boston_df2.iloc[i,:].values),';')
    

insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values (0, 4.09, 1.0, 296.0, 15.3, 396.9, 4.98) ;
insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values (1, 4.9671, 2.0, 242.0, 17.8, 396.9, 9.14) ;
insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values (2, 4.9671, 2.0, 242.0, 17.8, 392.83, 4.03) ;
insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values (3, 6.0622, 3.0, 222.0, 18.7, 394.63, 2.94) ;
insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values (4, 6.0622, 3.0, 222.0, 18.7, 396.9, 5.33) ;
insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values (5, 6.0622, 3.0, 222.0, 18.7, 394.12, 5.21) ;
insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values (6, 5.5605, 5.0, 311.0, 15.2, 395.6, 12.43) ;
insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values (7, 5.9505, 5.0, 311.0, 15.2, 396.9, 19.15) ;
insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values (8, 6.0821, 5.0, 311.0, 15.2, 386.63, 29.93) ;
inser

In [157]:
stmt='insert into boston_slave(seq,DIS,RAD,TAX,PTRATIO,B,LSTAT) values'

boston_df2.columns

Index(['DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='object')

In [164]:
df = pd.read_csv('https://datahub.io/five-thirty-eight/alcohol-consumption/r/drinks.csv')

In [165]:
df

country  beer_servings  spirit_servings  wine_servings  \
0    afghanistan              0                0              0   
1        albania             89              132             54   
2        algeria             25                0             14   
3        andorra            245              138            312   
4         angola            217               57             45   
..           ...            ...              ...            ...   
188    venezuela            333              100              3   
189      vietnam            111                2              1   
190        yemen              6                0              0   
191       zambia             32               19              4   
192     zimbabwe             64               18              4   

     total_litres_of_pure_alcohol  
0                             0.0  
1                             4.9  
2                             0.7  
3                            12.4  
4                             5.9  
..                            ...  
188                           7.7  
189                           2.0  
190                           0.1  
191                           2.5  
192                           4.7  

[193 rows x 5 columns]

In [170]:
df.dtypes

country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
dtype: object

In [174]:
stmt2='insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values'
for i in df.index:
    print(stmt2,tuple(df.iloc[i,:].values),';')

insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('afghanistan', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('albania', 89, 132, 54, 4.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('algeria', 25, 0, 14, 0.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('andorra', 245, 138, 312, 12.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('angola', 217, 57, 45, 5.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('antigua & barbuda', 102, 128, 45, 4.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,w

AttributeError: 'DataFrame' object has no attribute 'colnames'