## if

if 조건문:
    수행할 문장1
    수행할 문장2
    수행할 문장3

In [1]:
money = True
if money:
    print("택시를")
print("타고")
    print("가라")

IndentationError: unexpected indent (<ipython-input-1-82e621c85c37>, line 5)

In [1]:
money = 2000
if money >= 3000:
    print("택시를 타고 가라")
else:
    print("걸어가라")

걸어가라


In [2]:
money >= 3000

False

"돈이 3000원 이상 있거나 카드가 있다면 택시를 타고 그렇지 않으면 걸어 가라."

In [9]:
money = 2000
card = True
if money >= 3000 or card:
    print("택시를 타고 가라")
else:
    print("걸어가라")

택시를 타고 가라


In [7]:
1 in [1, 2, 3]

True

In [8]:
1 not in [1, 2, 3]

False

In [3]:
'a' in ('a', 'b', 'c')

True

In [6]:
'j' not in 'python'

True

"만약 주머니에 돈이 있으면 택시를 타고, 없으면 걸어 가라."

In [9]:
pocket = ['paper', 'cellphone', 'money']
if 'money' in pocket:
    print("택시를 타고 가라")
else:
    print("걸어가라")

택시를 타고 가라


In [2]:
pocket = ['paper', 'money', 'cellphone']
if 'money' in pocket:
    pass 
else:
    print("카드를 꺼내라")

"주머니에 돈이 있으면 택시를 타고, 주머니에 돈은 없지만 카드가 있으면 택시를 타고, 돈도 없고 카드도 없으면 걸어 가라." ==> elif

In [18]:
pocket = ['paper', 'cellphone']
card = False
if 'money' in pocket:
     print("택시를 타고가라")
elif card: 
     print("택시를 타고가라")
else:
     print("걸어가라")

걸어가라


In [14]:
pocket = ['paper', 'cellphone']
card = False
if 'money' in pocket: print("택시를 타고가라")
elif card: print("택시를 타고가라")
else: print("걸어가라")

걸어가라


In [4]:
score = 50

In [17]:
if score >= 60:
    message = "success"
else:
    message = "failure"

In [6]:
message = "success" if score >= 60 else "failure"
message

'failure'

**조건문이 참인 경우 if 조건문 else 조건문이 거짓인 경우

## while

while <조건문>:
    <수행할 문장1>
    <수행할 문장2>
    <수행할 문장3>

In [4]:
treeHit = 0
while treeHit < 10:
    treeHit = treeHit +1
    print("나무를 %d번 찍었습니다." % treeHit)
    if treeHit == 10:
        print("나무 넘어갑니다.")

나무를 1번 찍었습니다.
나무를 2번 찍었습니다.
나무를 3번 찍었습니다.
나무를 4번 찍었습니다.
나무를 5번 찍었습니다.
나무를 6번 찍었습니다.
나무를 7번 찍었습니다.
나무를 8번 찍었습니다.
나무를 9번 찍었습니다.
나무를 10번 찍었습니다.
나무 넘어갑니다.


In [24]:
treeHit = 0
while treeHit < 10:
    treeHit += 1
    print("나무를 %d번 찍었습니다." % treeHit)
    if treeHit == 10:
        print("나무 넘어갑니다.")

나무를 1번 찍었습니다.
나무를 2번 찍었습니다.
나무를 3번 찍었습니다.
나무를 4번 찍었습니다.
나무를 5번 찍었습니다.
나무를 6번 찍었습니다.
나무를 7번 찍었습니다.
나무를 8번 찍었습니다.
나무를 9번 찍었습니다.
나무를 10번 찍었습니다.
나무 넘어갑니다.


In [1]:
treeHit = 0
while treeHit < 10:
    print("나무를 %d번 찍었습니다." % treeHit)
    treeHit += 1
    if treeHit == 10: break

나무를 0번 찍었습니다.
나무를 1번 찍었습니다.
나무를 2번 찍었습니다.
나무를 3번 찍었습니다.
나무를 4번 찍었습니다.
나무를 5번 찍었습니다.
나무를 6번 찍었습니다.
나무를 7번 찍었습니다.
나무를 8번 찍었습니다.
나무를 9번 찍었습니다.


In [9]:
coffee = 10
money = 300
while money:
    coffee = coffee -1
    print("돈을 받았으니 커피를 줍니다.")
    print("남은 커피의 양은 %d개입니다." % coffee)
    if coffee == 0:
        #print("남은 커피의 양은 %d개입니다." % coffee)
        print("커피가 다 떨어졌습니다. 판매를 중지합니다.")
        break

돈을 받았으니 커피를 줍니다.
남은 커피의 양은 9개입니다.
돈을 받았으니 커피를 줍니다.
남은 커피의 양은 8개입니다.
돈을 받았으니 커피를 줍니다.
남은 커피의 양은 7개입니다.
돈을 받았으니 커피를 줍니다.
남은 커피의 양은 6개입니다.
돈을 받았으니 커피를 줍니다.
남은 커피의 양은 5개입니다.
돈을 받았으니 커피를 줍니다.
남은 커피의 양은 4개입니다.
돈을 받았으니 커피를 줍니다.
남은 커피의 양은 3개입니다.
돈을 받았으니 커피를 줍니다.
남은 커피의 양은 2개입니다.
돈을 받았으니 커피를 줍니다.
남은 커피의 양은 1개입니다.
돈을 받았으니 커피를 줍니다.
남은 커피의 양은 0개입니다.
커피가 다 떨어졌습니다. 판매를 중지합니다.


In [ ]:
## while문의 맨 처음으로 돌아가기 ==> continue

In [4]:
# continue 이용 홀수만 출력
a = 0
while a < 10:
    a = a + 1
    if a % 2 == 0:continue
    print(a)

1
3
5
7
9


## for

for 변수 in 리스트(또는 튜플, 문자열):
    수행할 문장1
    수행할 문장2

In [1]:
sum = 0 
for i in range(10): 
    sum = sum + i 
    
sum

45

In [23]:
# 간략 도움말 보기??

In [7]:
range(10)

range(0, 10)

In [10]:
range(1,5)

range(1, 5)

In [14]:
a = []
for i in range(1,5):
    a.append(i)
print(a)

[1, 2, 3, 4]


In [17]:
b = []
for i in range(1,6,2):
    b.append(i)
print(b)

[1, 3, 5]


In [28]:
sum = 0 
for i in range(1, 11): 
    sum = sum + i 

In [29]:
sum

55

### enumerate

In [37]:
p = ['money','card']
enumerate(p)

In [17]:
## enumerate 설명
p = ['money','card']

for idx, value in enumerate(p):
    print(idx, value)

0 money
1 card


In [23]:
for i in range(2,10):        # ①번 for문
    print("="*2,"%d 단" %i, "="*2)
    for j in range(1, 10):   # ②번 for문
        print("{} * {} = {}".format(i,j,i*j), end="\n") 
    print("")

== 2 단 ==
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18

== 3 단 ==
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27

== 4 단 ==
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36

== 5 단 ==
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45

== 6 단 ==
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54

== 7 단 ==
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63

== 8 단 ==
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72

== 9 단 ==
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81



In [62]:
a = [1,2,3,4]
result = []
for num in a:
    result.append(num*3)

In [65]:
result

[3, 6, 9, 12]

**리스트내포

In [13]:
a = [1,2,3,4]
result = [num * 3 for num in a]

In [11]:
a = [1,2,3,4]
result = []
for num in a:
    result.append(num*3)

In [15]:
a = [1,2,3,4]
result1 = [num * 3 for num in a if num >= 2]

In [16]:
result1

[6, 9, 12]

In [12]:
result

[3, 6, 9, 12]

만약 [1,2,3,4] 중에서 짝수에만 3을 곱하여 담고 싶다면 다음과 같이 리스트 내포 안에 "if 조건"을 사용할 수 있다.

In [ ]:
a = [1,2,3,4]
result = [num * 3 for num in a if num % 2 == 0]

## UDF

In [9]:
def add(a, b): 
    result = a + b 
    return result

In [44]:
a = add(3,4)

In [ ]:
# 결과값이 없는 함수

In [13]:
def adding(a, b): 
    print("%d, %d의 합은 %d입니다." % (a, b, a+b))

In [14]:
adding(3,5)

3, 5의 합은 8입니다.


In [17]:
b = adding(7,8)

7, 8의 합은 15입니다.


In [18]:
print(b)

None


In [ ]:
# 입력값이 몇개인지 정확히 모를 때

In [24]:
def add_many(*args): 
    result = 0 
    for i in args: 
        result = result + i 
    return result

In [25]:
add_many(5,6,7,8)

26

In [42]:
def add_mul(choice, *args): 
    if choice == "add": 
        result = 0 
        for i in args: 
            result = result + i 
    else: 
        result = 1 
        for i in args: 
            result = result * i 
    return result

In [43]:
add_mul("mul",1,2,3,4)

24

In [ ]:
## 함수의 결과값은 하나

In [26]:
def add_and_mul(a,b): 
    return a+b, a*b

In [68]:
add_and_mul(3,4)

(7, 12)

In [30]:
result1, result2 = add_and_mul(3,4)
result1

int

In [ ]:
## 함수 안 변수의 효력

In [6]:
a = 1
def vartest(a):
    a = a +1

In [7]:
vartest(a)

In [8]:
print(a)

1


In [9]:
def vartest(b):
    b = b +1

In [10]:
vartest(1)

In [ ]:
#### 방법1

In [13]:
a = 1
def vartest(a):
    a = a +1
    return a

In [14]:
a

1

In [15]:
vartest(1)

2

## print

In [2]:
print("life"+"is"+"too short")

lifeistoo short


In [3]:
print("life", "is", "too short")

life is too short


In [5]:
for i in range(10):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

## 연습

1. 1부터 1000까지의 자연수 중 3의 배수의 합을 구해보세요

2. 다음의 별 표시 프로그램을 작성해보세요  


*  
**  
***  
****  
*****  

3. for 문을 이용해 1부터 100까지 7의 배수 출력

4. A 반 총 10명의 중간고사 성적은
   [70, 60, 55, 75, 95, 90, 80, 80, 85, 100] 일 때,
   for 문 이용 A 학급의 평균 점수 구해보세요

5. 아래의 코드를 리스트 내포를 사용해 바꾸어 보세요

numbers = [1, 2, 3, 4, 5]
result = []
for n in numbers:
    if n % 2 == 1:
        result.append(n*2)

In [23]:
# 1.

i = 1
sum=0
result = []
while i<=1000:
    if i%3 == 0:2-1
        result.append(i)
        sum += i
    i = i+1
sum

166833

In [60]:
print(result," ")

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282, 285, 288, 291, 294, 297, 300, 303, 306, 309, 312, 315, 318, 321, 324, 327, 330, 333, 336, 339, 342, 345, 348, 351, 354, 357, 360, 363, 366, 369, 372, 375, 378, 381, 384, 387, 390, 393, 396, 399, 402, 405, 408, 411, 414, 417, 420, 423, 426, 429, 432, 435, 438, 441, 444, 447, 450, 453, 456, 459, 462, 465, 468, 471, 474, 477, 480, 483, 486, 489, 492, 495, 498, 501, 504, 507, 510, 513, 516, 519, 522, 525, 528, 531, 534, 537, 540, 543, 546, 549, 552, 555, 558, 561, 564, 567, 570, 573, 576, 579, 582, 585, 588, 591, 594, 597, 600, 603, 606, 609, 612, 615, 618, 621, 

In [43]:
res1 = [value % 3 == 0 for value in result]

np.unique(res1)
np.bincount(res1)

array([  0, 333], dtype=int64)

In [48]:
res2 = res1
res2[0] = False

np.unique(res2)
np.bincount(res2)

array([  1, 332], dtype=int64)

In [46]:
res2

[4,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 T

In [9]:
'% d' % 10

' 10'

In [13]:
i = 10
'{:>10d}'.format(i)

'        10'

In [14]:
'{:<10d}'.format(i)

'10        '

In [15]:
'{:^10d}'.format(i)

'    10    '

In [22]:
# 2.1

i = 1
while True:
    if i >= 6:break
    print('*' * i)
    i += 1

*
**
***
****
*****


In [1]:
for i in range(1,6):
    print('*'*i)

*
**
***
****
*****


In [14]:
# 2.2

i = 1
while True:
    if i >= 6:break
    print('{:>5s}'.format('*'*i))
    i = i+1

    *
   **
  ***
 ****
*****


In [3]:
for i in range(1,6):
    print(" "*(6-i) + "*"*i)

     *
    **
   ***
  ****
 *****


In [7]:
# 2.3

i = 9
while i>0:
    print('{:^9s}'.format('*'*i))
    i = i-2

*********
 ******* 
  *****  
   ***   
    *    


In [27]:
# 3.
for num in range(1,101):
    if num % 7 == 0:
        print(num)

7
14
21
28
35
42
49
56
63
70
77
84
91
98


In [21]:
# 3.1 리스트 내포

num1 = [n for n in range(1,101) if n % 7 ==0]

import numpy as np

num2 = np.array(num1).reshape(2,7)
print(num1)
print(num2)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]
[[ 7 14 21 28 35 42 49]
 [56 63 70 77 84 91 98]]


In [30]:
# 4.

A = [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
total = 0

for score in A:
    total += score

average = total / len(A)
print(average)

79.0


In [34]:
# 5.
numbers = [1, 2, 3, 4, 5]
result = [n*2 for n in numbers if n % 2 == 1]
print(result)

[2, 6, 10]
