### **module import**

In [326]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression 
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score


## **데이터 정리**

## **분석할 데이터 읽기**

In [84]:
df = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')

## 데이터 확인
df.columns
df.head(1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal.length    150 non-null float64
sepal.width     150 non-null float64
petal.length    150 non-null float64
petal.width     150 non-null float64
variety         150 non-null object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


## **데이터 전처리**

In [15]:
df.variety.unique()

y = np.where(df.variety == 'Setosa', 0, np.where(df.variety == 'Versicolor',1,2))

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
x = df.iloc[:,:-1]

In [24]:
x

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

## **모델 생성 및 학습**

In [28]:
svc_iris = SVC() ## 모델 생성
svc_iris.fit(x,y)

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

## **모델 평가**
## **평가 방법은 예측값과 실제값을 비교**

In [32]:
y_hat = svc_iris.predict(x)

In [37]:
sum(y == y_hat)/y.size

0.9866666666666667

## **모델 사용**

In [42]:
svc_iris.predict(np.array([6.7, 3.5, 5.1, 1.8]).reshape(1,4))

array([2])

## **Train set, Test set**

In [85]:
from sklearn.model_selection import train_test_split

In [86]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size = 0.2)

## **모델생성 및 학습**

In [87]:
svc_iris_train = SVC()
svc_iris_train.fit(X_train,Y_train)

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

## **모델평가**

In [88]:
y_hat = svc_iris_train.predict(X_test)
acc = accuracy_score(Y_test,y_hat)

In [89]:
acc

0.9666666666666667

In [63]:
from sklearn.preprocessing import LabelEncoder
X = df.iloc[:,:-1]
enc = LabelEncoder()

# ==================================================

# **TITANIC**

In [334]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

import seaborn as sns
df_2 = pd.read_csv('https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/fa71405126017e6a37bea592440b4bee94bf7b9e/titanic.csv')
df = sns.load_dataset('titanic')

In [335]:
df_2.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [336]:
dt = df_2.copy()

### **NA 데이터 채우기**

In [337]:
dt.Age.fillna(dt.Age.mean(), inplace=True)

In [338]:
dt[dt.Embarked.isnull()]

PassengerId  Survived  Pclass                                       Name  \
61            62         1       1                        Icard, Miss. Amelie   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
61   female  38.0      0      0  113572  80.0   B28      NaN  
829  female  62.0      0      0  113572  80.0   B28      NaN

In [339]:
dt.Embarked.fillna('N',inplace=True)

In [340]:
dt.Cabin.fillna('N',inplace=True)

In [341]:
dt.Cabin.str.slice(0,1).unique()

array(['N', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [342]:
dt['new_Cabin'] = dt.Cabin.str.slice(0,1)

In [343]:
dt.drop('Cabin',axis=1, inplace=True)

In [344]:
dt.drop(['PassengerId','Name','Ticket'], axis = 1, inplace=True)

In [345]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
Survived     891 non-null int64
Pclass       891 non-null int64
Sex          891 non-null object
Age          891 non-null float64
SibSp        891 non-null int64
Parch        891 non-null int64
Fare         891 non-null float64
Embarked     891 non-null object
new_Cabin    891 non-null object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB


In [346]:
dt.Embarked.unique()

array(['S', 'C', 'Q', 'N'], dtype=object)

In [347]:
dt.new_Cabin.unique()

array(['N', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

## **object column**
#### **Sex, Embarked, new_Cabin**

In [348]:
gender_enc = LabelEncoder()
gender = gender_enc.fit_transform(dt.Sex)
embark_enc = LabelEncoder()
embark = embark_enc.fit_transform(dt.Embarked)
cabin_enc = LabelEncoder()
cabin = cabin_enc.fit_transform(dt.new_Cabin)
pclass_enc = OneHotEncoder()
pclass = pclass_enc.fit_transform(dt.Pclass.values.reshape(-1,1)).toarray()

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [349]:
dt.drop(['Sex','Embarked','new_Cabin'], axis = 1, inplace = True)

In [350]:
dt['gender'] = gender
dt['embark'] = embark
dt['cabin'] = cabin

In [351]:
dt

Survived  Pclass        Age  SibSp  Parch     Fare  gender  embark  cabin
0           0       3  22.000000      1      0   7.2500       1       3      7
1           1       1  38.000000      1      0  71.2833       0       0      2
2           1       3  26.000000      0      0   7.9250       0       3      7
3           1       1  35.000000      1      0  53.1000       0       3      2
4           0       3  35.000000      0      0   8.0500       1       3      7
..        ...     ...        ...    ...    ...      ...     ...     ...    ...
886         0       2  27.000000      0      0  13.0000       1       3      7
887         1       1  19.000000      0      0  30.0000       0       3      1
888         0       3  29.699118      1      2  23.4500       0       3      7
889         1       1  26.000000      0      0  30.0000       1       0      2
890         0       3  32.000000      0      0   7.7500       1       2      7

[891 rows x 9 columns]

In [368]:
sc = StandardScaler()
age = sc.fit_transform(dt.Age.values.reshape(-1,1))

In [356]:
enc_data = np.concatenate([gender.reshape(-1,1), embark.reshape(-1,1), cabin.reshape(-1,1), pclass,age], axis = 1)

In [363]:
feature_col = ['SibSp','Parch','Fare']
dep_col = ['Survived']
X = pd.concat([dt[feature_col], pd.DataFrame(enc_data)],axis=1)
y = dt[dep_col]

In [364]:
X

SibSp  Parch     Fare    0    1    2    3    4    5         6
0        1      0   7.2500  1.0  3.0  7.0  0.0  0.0  1.0 -0.592481
1        1      0  71.2833  0.0  0.0  2.0  1.0  0.0  0.0  0.638789
2        0      0   7.9250  0.0  3.0  7.0  0.0  0.0  1.0 -0.284663
3        1      0  53.1000  0.0  3.0  2.0  1.0  0.0  0.0  0.407926
4        0      0   8.0500  1.0  3.0  7.0  0.0  0.0  1.0  0.407926
..     ...    ...      ...  ...  ...  ...  ...  ...  ...       ...
886      0      0  13.0000  1.0  3.0  7.0  0.0  1.0  0.0 -0.207709
887      0      0  30.0000  0.0  3.0  1.0  1.0  0.0  0.0 -0.823344
888      1      2  23.4500  0.0  3.0  7.0  0.0  0.0  1.0  0.000000
889      0      0  30.0000  1.0  0.0  2.0  1.0  0.0  0.0 -0.284663
890      0      0   7.7500  1.0  2.0  7.0  0.0  0.0  1.0  0.177063

[891 rows x 10 columns]

## **Train, Test**

In [366]:
X = dt.iloc[:,1:]
y = dt.iloc[:,0]

In [315]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression 
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

## **모델 생성 및 학습**

In [309]:
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

## **모델평가**

In [310]:
y_hat = dt_clf.predict(X_test)
acc = accuracy_score(y_test, y_hat)
acc

0.8156424581005587

# **SVC**

## **모델 생성 및 학습**

In [311]:
dt_svc = SVC()
dt_svc.fit(X_train,y_train)

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [318]:
dt_svc = SVC(C=0.3, kernel = 'linear')
dt_svc.fit(X_train,y_train)

SVC(C=0.3, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

## **모델평가**

In [319]:
y_hat = dt_svc.predict(X_test)
acc = accuracy_score(y_test,y_hat)
acc

0.7150837988826816

## **여러번 돌리기**

In [322]:
test_acc =[]
for _ in np.arange(5):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)
    dt_tree = DecisionTreeClassifier()
    dt_tree.fit(X_train, y_train)
    acc = accuracy_score(dt_tree.predict(X_test),y_test)
   # dt_svc = SVC(C=0.3, kernel = 'linear')
   # dt_svc.fit(X_train,y_train)
   # acc = accuracy_score(dt_svc.predict(X_test),y_test)
    test_acc.append(acc)
sum(test_acc)/5

0.7608938547486034

In [327]:
sc = StandardScaler()
age = sc.fit_transform(dt.Age.values.reshape(-1,1))

In [330]:
enc_

array([[-0.5924806 ],
       [ 0.63878901],
       [-0.2846632 ],
       [ 0.40792596],
       [ 0.40792596],
       [ 0.        ],
       [ 1.87005862],
       [-2.13156761],
       [-0.20770885],
       [-1.20811541],
       [-1.97765891],
       [ 2.17787603],
       [-0.7463893 ],
       [ 0.71574336],
       [-1.20811541],
       [ 1.94701297],
       [-2.13156761],
       [ 0.        ],
       [ 0.10010856],
       [ 0.        ],
       [ 0.40792596],
       [ 0.33097161],
       [-1.13116105],
       [-0.1307545 ],
       [-1.66984151],
       [ 0.63878901],
       [ 0.        ],
       [-0.82334365],
       [ 0.        ],
       [ 0.        ],
       [ 0.79269771],
       [ 0.        ],
       [ 0.        ],
       [ 2.79351083],
       [-0.1307545 ],
       [ 0.94660642],
       [ 0.        ],
       [-0.66943495],
       [-0.900298  ],
       [-1.20811541],
       [ 0.79269771],
       [-0.20770885],
       [ 0.        ],
       [-2.05461326],
       [-0.82334365],
       [ 0