### **2.1 Logistic Regression**  
- Parameter C를 조정해 과대적합 혹은 과소적합 문제를 해결  
- C(cost function) 값이 크면(높은 코스트) --> 훈련을 더 복잡하게 --> 약한 규제  
- C값이 작으면(낮은 코스트) --> 훈련을 덜 복잡하게 --> 강한 규제

In [61]:
X_test[:, np.newaxis,0]

array([[5. ],
       [6.7],
       [6.6],
       [5.5],
       [6.9],
       [5.7],
       [6. ],
       [6.7],
       [6.3],
       [6.5],
       [5.9],
       [5.8],
       [7.9],
       [6.3],
       [4.9],
       [5.5],
       [6.2],
       [6.5],
       [5.8],
       [6.3],
       [5.6],
       [7.2],
       [6.8],
       [6.7],
       [6.3],
       [6.4],
       [6.3],
       [5.6],
       [4.9],
       [7.3]])

In [59]:
iris_dataset.data
X_test[:, np.newaxis,0]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
?LogisticRegression

Init signature:
LogisticRegression(
    penalty='l2',
    dual=False,
    tol=0.0001,
    C=1.0,
    fit_intercept=True,
    intercept_scaling=1,
    class_weight=None,
    random_state=None,
    solver='warn',
    max_iter=100,
    multi_class='warn',
    verbose=0,
    warm_start=False,
    n_jobs=None,
    l1_ratio=None,
)
Docstring:     
Logistic Regression (aka logit, MaxEnt) classifier.

In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
scheme if the 'multi_class' option is set to 'ovr', and uses the
cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
(Currently the 'multinomial' option is supported only by the 'lbfgs',
'sag', 'saga' and 'newton-cg' solvers.)

This class implements regularized logistic regression using the
'liblinear' library, 'newton-cg', 'sag', 'saga' and 'lbfgs' solvers. **Note
that regularization is applied by default**. It can handle both dense
and sparse input. Use C-ordered arrays or CSR matrices containing 64-bi

#### **2.1.1 Iris**

In [5]:
# 1. 데이터 불러오기
iris_dataset = datasets.load_iris()

In [6]:
# 2. 데이터 분할 - 이항분류  
X = iris_dataset.data[50:,:]
y = iris_dataset.target[50:]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 58)

In [7]:
X_train.shape

(70, 4)

In [8]:
# 3. modeling
logreg = LogisticRegression().fit(X_train, y_train)
logreg

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
# 4. 결과 비교
print('train set score : {:.3f}'.format(logreg.score(X_train, y_train)))
print('test set score : {:.3f}'.format(logreg.score(X_test, y_test)))

train set score : 0.986
test set score : 0.933


In [55]:
# 5. parameter tuning
logreg001 = LogisticRegression(solver = 'lbfgs', C = 0.01).fit(X_train, y_train)
logreg001
logreg100 = LogisticRegression(solver = 'lbfgs', C = 100).fit(X_train, y_train)
logreg100

LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [56]:
# 5.1 C = 0.01 결과 비교 --> 낮은 코스트 --> 훈련 덜 복잡 --> 강한 규제
print('train set score : {:.3f}'.format(logreg001.score(X_train, y_train)))
print('test set score : {:.3f}'.format(logreg001.score(X_test, y_test)))

train set score : 0.914
test set score : 0.900


In [57]:
# 5.2 C = 100 결과 비교 --> 높은 코스트 --> 훈련 더 복잡 --> 약한 규제
print('train set score : {:.3f}'.format(logreg100.score(X_train, y_train)))
print('test set score : {:.3f}'.format(logreg100.score(X_test, y_test)))

train set score : 0.986
test set score : 0.900


## **역으로 계산하여 predict_proba()와 비교해보기**

In [25]:
logreg.coef_

array([[-1.51169047, -1.34432386,  2.12855352,  2.31350688]])

In [26]:
logreg.coef_[0][0] * X_test[:,0]

array([ -7.55845235, -10.12832615,  -9.97715711,  -8.31429759,
       -10.43066425,  -8.61663568,  -9.07014282, -10.12832615,
        -9.52364996,  -9.82598806,  -8.91897378,  -8.76780473,
       -11.94235472,  -9.52364996,  -7.40728331,  -8.31429759,
        -9.37248092,  -9.82598806,  -8.76780473,  -9.52364996,
        -8.46546664, -10.88417139, -10.2794952 , -10.12832615,
        -9.52364996,  -9.67481901,  -9.52364996,  -8.46546664,
        -7.40728331, -11.03534044])

In [33]:
logreg.coef_[0][0] * X_test[:, np.newaxis,0] + \
logreg.coef_[0][1] * X_test[:, np.newaxis,1] + \
logreg.coef_[0][2] * X_test[:, np.newaxis,2] + \
logreg.coef_[0][3] * X_test[:, np.newaxis,3] + logreg.intercept_


array([[-2.28110726],
       [ 2.05234349],
       [-2.04523468],
       [-2.31996347],
       [ 1.75287678],
       [-1.90191774],
       [ 1.11692909],
       [ 1.25980288],
       [ 3.62672611],
       [-1.29693187],
       [ 0.19211563],
       [-1.94106795],
       [ 0.23052739],
       [ 1.69357942],
       [ 1.77491606],
       [-1.87575743],
       [ 0.27633804],
       [ 0.38636879],
       [-2.32534636],
       [ 2.40952162],
       [-0.41813057],
       [ 0.78118225],
       [-1.556079  ],
       [-2.65962852],
       [ 0.06968298],
       [ 1.6573006 ],
       [ 0.04726944],
       [-1.94850351],
       [-2.2643706 ],
       [ 1.67187642]])

In [34]:
odds = np.exp(logreg.coef_[0][0] * X_test[:, np.newaxis, 0] + 
             logreg.coef_[0][1] * X_test[:, np.newaxis, 1] + 
             logreg.coef_[0][2] * X_test[:, np.newaxis, 2] + 
             logreg.coef_[0][3] * X_test[:, np.newaxis, 3] + logreg.intercept_)

In [35]:
final_values = odds/(1 + odds)
final_values

array([[0.09269978],
       [0.8861842 ],
       [0.11453478],
       [0.08948304],
       [0.85231528],
       [0.12989158],
       [0.75341865],
       [0.77899217],
       [0.97408625],
       [0.21468183],
       [0.54788173],
       [0.12553058],
       [0.55737797],
       [0.84469431],
       [0.85506797],
       [0.13287694],
       [0.56864822],
       [0.59540825],
       [0.08904543],
       [0.9175505 ],
       [0.39696417],
       [0.68593486],
       [0.17421001],
       [0.06539804],
       [0.5174137 ],
       [0.83987531],
       [0.51181516],
       [0.12471663],
       [0.09411707],
       [0.84182584]])

In [36]:
temp = logreg.predict_proba(X_test)

In [37]:
np.round(temp[:, np.newaxis, 1], 3) == np.round(final_values, 3)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [54]:
temp

array([[0.90730022, 0.09269978],
       [0.1138158 , 0.8861842 ],
       [0.88546522, 0.11453478],
       [0.91051696, 0.08948304],
       [0.14768472, 0.85231528],
       [0.87010842, 0.12989158],
       [0.24658135, 0.75341865],
       [0.22100783, 0.77899217],
       [0.02591375, 0.97408625],
       [0.78531817, 0.21468183],
       [0.45211827, 0.54788173],
       [0.87446942, 0.12553058],
       [0.44262203, 0.55737797],
       [0.15530569, 0.84469431],
       [0.14493203, 0.85506797],
       [0.86712306, 0.13287694],
       [0.43135178, 0.56864822],
       [0.40459175, 0.59540825],
       [0.91095457, 0.08904543],
       [0.0824495 , 0.9175505 ],
       [0.60303583, 0.39696417],
       [0.31406514, 0.68593486],
       [0.82578999, 0.17421001],
       [0.93460196, 0.06539804],
       [0.4825863 , 0.5174137 ],
       [0.16012469, 0.83987531],
       [0.48818484, 0.51181516],
       [0.87528337, 0.12471663],
       [0.90588293, 0.09411707],
       [0.15817416, 0.84182584]])